### ISSUE TITLE
Missing attribution for Apache and Apache Kafka

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious.github.io#24]
I believe we ought to be attributing the Apache and Apache Kafka marks in our footer, as per:

https://www.apache.org/foundation/marks/faq/#attribution

I think we are already complying with name with respect to prominent use the full form of the Apache Kafka name, I wonder if we ought to be using the ® symbol too, on the first use.

https://www.apache.org/foundation/marks/guide#naming

**Comment by k-wall** [comment]
@gracegrimwood @insectengine FYI

**Comment by insectengine** [comment]
Better safe than sorry. I've put in a PR.

https://github.com/kroxylicious/kroxylicious.github.io/pull/28

**Comment by k-wall** [comment]
Closed by #28
