### ISSUE TITLE
Add table of content for the use case content

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious.github.io#30]
To help the reader navigate, we'd like the use-case content to have a table of contents.

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious.github.io/pull/25#pullrequestreview-1840238208_

**Comment by SamBarker** [comment]
This was take care of by @gracegrimwood PR against your branch (it may not be noticeable with the change to move the other use cases to the drafts folder)
